import Head from 'next/head'
import Navbar from '../components/Navbar';

import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Côncavo Photography</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
